# Generated by Django 2.1.7 on 2019-07-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiofield', '0002_auto_20180121_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'permissions': (('view_audiofile_perm', 'can see Audio Files'),), 'verbose_name': 'audio file', 'verbose_name_plural': 'audio files'},
        ),
    ]
